### ISSUE TITLE
Form controls squeezed out in Firefox

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/ala-bootstrap3#11]
The offending item is ala-styles.css which has

```
.form-control {border-radius: 0;padding: 18.5px 12px;border: 1px solid #999;}
```
The padding reduces the text box to 0 height. Firefox honours this and doesn't show the form value. Chrome and Safari still show the form entry.

**Comment by matthewandrews** [comment]
This should be happier now - deployed a change to ala-styles to remove padding from `.form-control` and apply to `textarea.form-control` and `input-lg` only.
