### ISSUE TITLE
Caching intermittently fails for head.html

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ala-bootstrap3#19]
The caching is failing intermittently (days or weeks between episodes) for the commonui head.html file. When it does occur, it causes a large number of queries to go into `www.ala.org.au`, possibly related to the number of queries going into lists. There were 66,265 queries on Friday during a DDoS attack from lists to www, where the number of requests for the commonui head.html should never scale with traffic received if the caching is working correctly.

This is the last 7 days of requests between lists and www for the commonui elements:

<img width="729" alt="Screen Shot 2020-07-20 at 9 54 21 am" src="https://user-images.githubusercontent.com/82365/87888403-1246d000-ca70-11ea-988d-537f3347bef3.png">

This is the last 90 days of requests between lists and www for the commonui elements:

<img width="730" alt="Screen Shot 2020-07-20 at 9 55 37 am" src="https://user-images.githubusercontent.com/82365/87888428-33a7bc00-ca70-11ea-819c-35ca37b522a9.png">

The issue is localised to `head.html`, as this 90 day graph shows:

<img width="1457" alt="Screen Shot 2020-07-20 at 9 56 07 am" src="https://user-images.githubusercontent.com/82365/87888433-39050680-ca70-11ea-8d7b-23aa55c9b113.png">

**Comment by matthewandrews** [comment]
`head.html` is a blank file.  Do we even need these requests?

**Comment by ansell** [comment]
If the file request code is removed here and everything using this library has this plugin upgraded to the new version that doesn't request it, this issue would go away (at least for BS3).

**Comment by Rita-C** [comment]
head.html updated by @matthewandrews . @ansell I've tested on my local page loads it seems the problem is resolved.

**Comment by ansell** [comment]
Thanks Rita, leaving this open and assigned to Matt to patch the other `head.html` files (commonui-bs2/etc.) later today.

**Comment by matthewandrews** [comment]
I've now added/edited `head.html` in all current `commonui` (`-bs2`, `-bs3`, which I think is unused, and `-bs3-2019`) and deployed to test and prod.

**Comment by ansell** [comment]
Thanks
