### ISSUE TITLE
Keep cached template copy as long as possible

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ala-bootstrap3#20]
Rather than wiping the template cache before fetching, we should be keeping the cached copy for as long as possible to avoid www.ala.org.au outages from causing other applications to crash.

**Comment by ansell** [comment]
Code that may be relevant to this issue is at:

https://github.com/AtlasOfLivingAustralia/ala-bootstrap3/blob/master/grails-app/taglib/au/org/ala/bootstrap3/HeaderFooterTagLib.groovy#L139-L171

**Comment by Rita-C** [comment]
Hi @ansell,
Was the issue that page was not displayed properly if the template was not fetched and the cached one was removed?

**Comment by ansell** [comment]
Yes, in some cases the entire website fails currently because the cached copy is removed before a new template is successfully fetched.

**Comment by Rita-C** [comment]
@nickdos @ansell , I created a branch there is no dev, do we need to update the version number for this change?

**Comment by ansell** [comment]
Yes, this will need a new version number to release the new version of the plugin.

**Comment by nickdos** [comment]
Is this ready for QA?

**Comment by ansell** [comment]
It may need to be integrated into an application first.

**Comment by Rita-C** [comment]
PR for @sbearcsiro to review, I've tested it locally as an embedded plugin in `lists`, not sure how/where to deploy the change.

**Comment by nickdos** [comment]
@Rita-C if you deploy lists-test.ala.org.au I could QA test it there. This might need a separate commonui-bs3 test set of template files to point to, depending on the nature of the changes.

**Comment by ansell** [comment]
@matthewandrews What is the best test system to point to for commonui that we could take offline for a few hours to test whether the caching fix is working?
