### ISSUE TITLE
Merge and test patch from QCIF

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ala-bootstrap3#21]
See Slack message: https://atlaslivingaustralia.slack.com/archives/C015H7ZGTV3/p1599196804002100

Probably need more details for testing this...

Se also: https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/723

**Comment by ansell** [comment]
The patch moves the caching code related to https://github.com/AtlasOfLivingAustralia/ala-bootstrap3/issues/20 to a new class, but it still needs changes to make the caching code more resilient.

**Comment by nickdos** [comment]
Seeing as @Rita-C has made commits to the caching code, the patch code probably won't work now... will need to be done to an older version of the code and then the changes manually copied over, I'm guessing.

EDIT: added patch to this private issue https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/723

**Comment by ansell** [comment]
Applying the patch to the 3.2.2 tag should work https://github.com/AtlasOfLivingAustralia/ala-bootstrap3/releases/tag/3.2.2 and then a git merge will show the conflicts after that point.

**Comment by ansell** [comment]
Just to clarify, if others are concerned about the merge conflict, I am fairly confident in resolving merge conflicts and could try the merge (but not the testing/release afterwards).

**Comment by Rita-C** [comment]
will try Peter's suggestion. probably need more testing details.
