### ISSUE TITLE
Update templates to support HTTPS

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ala-bootstrap3#3]
Plan is to move to "HTTPS everywhere", so we need this plugin to support that by using the `//host/path` style of URIs in `src` and `href` attributes.

**Comment by ansell** [comment]
This looks like it is fixed now, although not using the schema-less URLs, by directly referencing ``https://`` instead. We are also using ``HSTS`` and ``Content-Security-Policy: upgrade-insecure-requests`` to silently resolve any transition issues on modern browsers along with HTTP 301 redirects from HTTP to HTTPS for initial requests.
